### ISSUE TITLE
Links are Broken

### ISSUE THREAD

**Issue by infection-tag** [infection-tag/learn-c#1]

**Comment by 0xPranjl** [comment]
i have fixed the links and opened a pull request

**Comment by infection-tag** [comment]
@0xPranjl Thanks for your help, but there still seems to be a bit of a bug: the [chapter one main page](https://infection-tag.github.io/learn-c/Chapter%20One%20Basics%20and%20Loops.html) seems to redirect to a markdown version of the site (which isn't supported by GitHub pages). The only forseeable solution is to manually swap the "next"/"previous" links and others, which I suppose I will do eventually.

**Comment by infection-tag** [comment]
I have gone over everything and manually fixed links. It should now be easy to use and should work like a normal website.
